// Catalogue Instru Shop.
window.SHOP = {
  name: 'Instru Shop',
  server: 'Peurle SMP',
  owner: 'InstructeurMc',
  description: 'Bienvenue à tous chez l’Instru Shop ! Le plus grand magasin de tout Peurle SMP.\nIci, vous découvrirez ce qu’est vraiment la variété.',
  draft: false,
  orderMode: 'discord', // catalogue, ingame ou discord
  discord: 'therescaper',
  products: [
    { id: 'armure', name: 'Armure complète en diamant', category: 'Armures', image: 'diamond_chestplate', images: ['diamond_helmet','diamond_chestplate','diamond_leggings','diamond_boots'], description: 'Casque, plastron, jambières et bottes.', unit: 'ensemble de 4 pièces', prices: { diamants: 12 } },
    { id: 'pioche', name: 'Pioche en diamant', category: 'Outils', image: 'diamond_pickaxe', description: 'Efficacité 2 offerte pour tout achat de pioche.', unit: 'pièce', prices: { fer: 8, or: 8 } },
    { id: 'hache', name: 'Hache en diamant', category: 'Outils', image: 'diamond_axe', description: 'Efficacité 2 offerte pour tout achat de hache.', unit: 'pièce', prices: { fer: 8, or: 8 } },
    { id: 'houe', name: 'Houe en diamant', category: 'Outils', image: 'diamond_hoe', description: 'Pour préparer tes champs avec du bon matériel.', unit: 'pièce', prices: { fer: 8, or: 8 } },
    { id: 'epee', name: 'Épée en diamant', category: 'Armes', image: 'diamond_sword', description: 'Tranchant 3, Solidité 3 et Recul 2 offerts pour tout achat.', unit: 'pièce', prices: { fer: 8, or: 8 } },
    { id: 'pelle', name: 'Pelle en diamant', category: 'Outils', image: 'diamond_shovel', description: 'Toucher de soie (Silk Touch) offert pour tout achat.', unit: 'pièce', prices: { fer: 8, or: 8 } },
    { id: 'bouclier', name: 'Bouclier enchanté', category: 'Équipement', image: 'shield', description: 'Solidité III (Unbreaking III) + Raccommodage (Mending).', unit: 'pièce', details: 'Solidité III + Raccommodage', prices: { diamants: 5, fer: 32, or: 32 } },
    { id: 'arc-power-2', name: 'Arc Puissance 2', category: 'Armes', image: 'bow', description: 'Arc enchanté Puissance 2 pour mieux défendre ta base.', unit: 'pièce', details: 'Puissance 2', prices: { fer: 4, or: 4 } },
    { id: 'fleches', name: 'Flèches', category: 'Armes', image: 'arrow', description: 'De quoi remplir ton carquois avant une expédition.', unit: 'lot de 64', prices: { fer: 1, or: 1 } },
    { id: 'arbalete-multishot', name: 'Arbalète Multishot', category: 'Armes', image: 'crossbow', description: 'Arbalète enchantée Multishot pour tirer plusieurs projectiles.', unit: 'pièce', details: 'Multishot', prices: { fer: 4, or: 4 } },
    { id: 'carotte', name: 'Carottes dorées', category: 'Nourriture', image: 'golden_carrot', description: 'De quoi garder tes réserves bien remplies.', unit: 'lot de 32', prices: { fer: 12, or: 12, diamants: 6 } },
    { id: 'pommes', name: 'Pommes', category: 'Nourriture', image: 'apple', description: 'Des pommes simples pour compléter tes réserves.', unit: 'lot de 64', prices: { fer: 8, or: 8 } },
    { id: 'pain', name: 'Pain', category: 'Nourriture', image: 'bread', description: 'Du ravitaillement pour tes expéditions.', unit: 'lot de 64', prices: { fer: 8, or: 8 } },
    { id: 'perle', name: 'Perles de l’Ender', category: 'Ressources', image: 'ender_pearl', description: 'Pour te téléporter ou préparer tes crafts.', unit: 'lot de 16', prices: { fer: 32, or: 32, diamants: 8 } },
    { id: 'xp', name: 'Fioles d’expérience', category: 'Enchantement', image: 'experience_bottle', description: 'Quelques points d’expérience à portée de main.', unit: 'lot de 24', prices: { fer: 12, or: 12 } },
    { id: 'lapis', name: 'Lapis-lazuli', category: 'Enchantement', image: 'lapis_lazuli', description: 'Pour ta table d’enchantement et tes teintures.', unit: 'lot de 32', prices: { fer: 8, or: 8, diamants: 2 } },
    { id: 'redstone', name: 'Redstone', category: 'Ressources', image: 'redstone', description: 'De la poudre de redstone pour tes circuits et mécanismes.', unit: 'lot de 32', prices: { fer: 8, or: 8, diamants: 2 } },
    { id: 'glowstone', name: 'Glowstone', category: 'Construction', image: 'glowstone', description: 'Des blocs de pierre lumineuse pour tes builds.', unit: 'lot de 32 blocs', prices: { fer: 8, or: 8 } },
    { id: 'verre', name: 'Verre', category: 'Construction', image: 'glass', description: 'Des blocs de verre pour tes constructions.', unit: 'lot de 64 blocs', prices: { fer: 8, or: 8 } },
    { id: 'chiseled-stone-bricks', name: 'Briques de pierre sculptées', category: 'Construction', image: 'chiseled_stone_bricks', description: 'Des blocs sculptés pour tes builds médiévaux.', unit: 'lot de 64 blocs', prices: { fer: 8, or: 8 } },
    { id: 'briques', name: 'Briques', category: 'Construction', shelf: 'Ressources', image: 'brick', description: 'Des briques simples pour tes crafts et builds.', unit: 'lot de 64', prices: { fer: 2, or: 2 } },
    { id: 'polished-granite', name: 'Granite poli', category: 'Construction', image: 'polished_granite', description: 'Des blocs polis aux tons chauds.', unit: 'lot de 64 blocs', prices: { fer: 8, or: 8 } },
    { id: 'polished-andesite', name: 'Andésite polie', category: 'Construction', image: 'polished_andesite', description: 'Des blocs gris propres pour tes sols et murs.', unit: 'lot de 64 blocs', prices: { fer: 8, or: 8 } },
    { id: 'dripstone-block', name: 'Bloc de spéléothème', category: 'Construction', image: 'dripstone_block', description: 'Des blocs naturels pour grottes et décorations.', unit: 'lot de 64 blocs', prices: { fer: 8, or: 8 } },
    { id: 'brown-glazed-terracotta', name: 'Terre cuite émaillée marron', category: 'Construction', image: 'brown_glazed_terracotta', description: 'Un bloc décoratif marron avec motif.', unit: 'lot de 32 blocs', prices: { fer: 8, or: 8 } },
    { id: 'cyan-glazed-terracotta', name: 'Terre cuite émaillée cyan', category: 'Construction', image: 'cyan_glazed_terracotta', description: 'Un bloc décoratif cyan avec motif.', unit: 'lot de 32 blocs', prices: { fer: 8, or: 8 } },
    { id: 'lime-terracotta', name: 'Terre cuite vert clair', category: 'Construction', image: 'lime_terracotta', description: 'De la terre cuite colorée pour tes builds.', unit: 'lot de 32 blocs', prices: { fer: 8, or: 8 } },
    { id: 'quartz-pillar', name: 'Pilier de quartz', category: 'Construction', image: 'quartz_pillar', description: 'Des piliers blancs pour temples et entrées.', unit: 'lot de 32 blocs', prices: { fer: 8, or: 8 } },
    { id: 'quartz-block', name: 'Bloc de quartz', category: 'Construction', image: 'quartz_block', description: 'Des blocs blancs propres pour constructions modernes.', unit: 'lot de 32 blocs', prices: { fer: 8, or: 8 } },
    { id: 'pink-terracotta', name: 'Terre cuite rose', category: 'Construction', image: 'pink_terracotta', description: 'De la terre cuite rose pour décorations colorées.', unit: 'lot de 32 blocs', prices: { fer: 8, or: 8 } },
    { id: 'orange-terracotta', name: 'Terre cuite orange', category: 'Construction', image: 'orange_terracotta', description: 'De la terre cuite orange pour builds chauds.', unit: 'lot de 32 blocs', prices: { fer: 8, or: 8 } },
    { id: 'yellow-terracotta', name: 'Terre cuite jaune', category: 'Construction', image: 'yellow_terracotta', description: 'De la terre cuite jaune pour builds lumineux.', unit: 'lot de 32 blocs', prices: { fer: 8, or: 8 } },
    { id: 'bougies-rouges', name: 'Bougies rouges', category: 'Construction', image: 'red_candle', description: 'Des bougies rouges pour éclairage et décoration.', unit: 'lot de 32', prices: { fer: 6, or: 6 } },
    { id: 'bougies-jaunes', name: 'Bougies jaunes', category: 'Construction', image: 'yellow_candle', description: 'Des bougies jaunes pour éclairage et décoration.', unit: 'lot de 32', prices: { fer: 6, or: 6 } },
    { id: 'bannieres-blanches', name: 'Bannières blanches', category: 'Construction', image: 'white_banner', description: 'Des bannières blanches pour décorations et marqueurs.', unit: 'lot de 10', prices: { fer: 2, or: 2 } },
    { id: 'bannieres-rouges', name: 'Bannières rouges', category: 'Construction', image: 'red_banner', description: 'Des bannières rouges pour décorations et marqueurs.', unit: 'lot de 10', prices: { fer: 2, or: 2 } },
    { id: 'lanternes', name: 'Lanternes', category: 'Construction', image: 'lantern', description: 'Pour éclairer tes bases avec style.', unit: 'lot de 24', prices: { fer: 8, or: 8 } },
    { id: 'cloches', name: 'Cloches', category: 'Construction', image: 'bell', description: 'Pour décorer tes villages et tes shops.', unit: 'lot de 8', prices: { fer: 2, or: 2 } },
    { id: 'potions', name: 'Potions au choix', category: 'Potions', image: 'potion', description: 'Choisis tes 3 potions et précise ton choix sur Discord.', unit: 'lot de 3', details: 'Potions à préciser sur Discord', prices: { diamants: 2 } },
    { id: 'miel', name: 'Rayons de miel', category: 'Ressources', image: 'honeycomb', description: 'Pour tes bougies et tes constructions en cuivre ciré.', unit: 'lot de 64', prices: { fer: 8, or: 8, diamants: 2 } },
    { id: 'livres', name: 'Livres', category: 'Enchantement', image: 'book', description: 'Pour tes enchantements et tes bibliothèques.', unit: 'lot de 32', prices: { fer: 12, or: 12 } },
    { id: 'bibliotheques', name: 'Bibliothèques', category: 'Enchantement', image: 'bookshelf', description: 'Pour aménager ton espace d’enchantement.', unit: 'lot de 16', prices: { fer: 20, or: 20 } },
    { id: 'ench-unbreaking-3', name: 'Solidité 3 (Unbreaking 3)', category: 'Livre enchanté', shelf: 'Enchantements', image: 'enchanted_book', description: 'Ralentit l’usure de ton équipement pendant l’utilisation.', unit: 'livre', prices: { fer: 20, or: 20, diamants: 2 } },
    { id: 'ench-quick-charge-3', name: 'Charge rapide 3 (Quick Charge 3)', category: 'Livre enchanté', shelf: 'Enchantements', image: 'enchanted_book', description: 'Recharge ton arbalète beaucoup plus rapidement.', unit: 'livre', prices: { fer: 20, or: 20, diamants: 2 } },
    { id: 'ench-silk-touch', name: 'Toucher de soie (Silk Touch)', category: 'Livre enchanté', shelf: 'Enchantements', image: 'enchanted_book', description: 'Récupère certains blocs dans leur forme originale.', unit: 'livre', prices: { fer: 20, or: 20, diamants: 2 } },
    { id: 'ench-punch-2', name: 'Frappe 2 (Punch 2)', category: 'Livre enchanté', shelf: 'Enchantements', image: 'enchanted_book', description: 'Repousse fortement les ennemis touchés par tes flèches.', unit: 'livre', prices: { fer: 20, or: 20, diamants: 2 } },
    { id: 'ench-knockback-2', name: 'Recul 2 (Knockback 2)', category: 'Livre enchanté', shelf: 'Enchantements', image: 'enchanted_book', description: 'Projette plus loin les ennemis frappés à l’épée.', unit: 'livre', prices: { fer: 20, or: 20, diamants: 2 } },
    { id: 'ench-fortune-3', name: 'Fortune 3', category: 'Livre enchanté', shelf: 'Enchantements', image: 'enchanted_book', description: 'Augmente les minerais et ressources obtenus en minant.', unit: 'livre', prices: { fer: 20, or: 20, diamants: 2 } },
    { id: 'ench-flame', name: 'Flamme (Flame)', category: 'Livre enchanté', shelf: 'Enchantements', image: 'enchanted_book', description: 'Enflamme les cibles touchées par tes flèches.', unit: 'livre', prices: { fer: 20, or: 20, diamants: 2 } },
    { id: 'ench-infinity', name: 'Infinité (Infinity)', category: 'Livre enchanté', shelf: 'Enchantements', image: 'enchanted_book', description: 'Tire des flèches sans consommer ton stock.', unit: 'livre', prices: { fer: 20, or: 20, diamants: 2 } },
    { id: 'ench-looting-3', name: 'Butin 3 (Looting 3)', category: 'Livre enchanté', shelf: 'Enchantements', image: 'enchanted_book', description: 'Augmente les drops obtenus sur les créatures tuées.', unit: 'livre', prices: { fer: 20, or: 20, diamants: 2 } },
    { id: 'ench-protection-4', name: 'Protection 4', category: 'Livre enchanté', shelf: 'Enchantements', image: 'enchanted_book', description: 'Réduit les dégâts reçus sur ton armure.', unit: 'livre', prices: { fer: 32, or: 32, diamants: 6 } },
    { id: 'ench-smite-5', name: 'Châtiment 5 (Smite 5)', category: 'Livre enchanté', shelf: 'Enchantements', image: 'enchanted_book', description: 'Inflige plus de dégâts aux morts-vivants.', unit: 'livre', prices: { fer: 32, or: 32, diamants: 6 } },
    { id: 'ench-channeling', name: 'Canalisation (Channeling)', category: 'Livre enchanté', shelf: 'Enchantements', image: 'enchanted_book', description: 'Fait tomber la foudre avec un trident sous orage.', unit: 'livre', prices: { fer: 20, or: 20, diamants: 2 } },
    { id: 'ench-mending', name: 'Raccommodage (Mending)', category: 'Livre enchanté', shelf: 'Enchantements', image: 'enchanted_book', description: 'Répare ton équipement avec l’expérience ramassée.', unit: 'livre', prices: { fer: 32, or: 32, diamants: 6 } },
    { id: 'ench-sharpness-5', name: 'Tranchant 5 (Sharpness 5)', category: 'Livre enchanté', shelf: 'Enchantements', image: 'enchanted_book', description: 'Augmente les dégâts de ton épée ou ta hache.', unit: 'livre', prices: { fer: 32, or: 32, diamants: 6 } },
    { id: 'ench-loyalty-3', name: 'Loyauté 3 (Loyalty 3)', category: 'Livre enchanté', shelf: 'Enchantements', image: 'enchanted_book', description: 'Ramène ton trident vers toi après le lancer.', unit: 'livre', prices: { fer: 20, or: 20, diamants: 2 } }
  ]
};
